# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YH9giOuGsRrmLvbIlykn_3v-fAfO2hz7
"""

// if else

if 10<20:
    print('yes')

if 10==20:
    print('Hassan')
else:
    print('Siddhu')

if 1==2:
  print('Hassan')
elif 3==3:
  print('Siddhu')
else:
  print('jutt')

list=[1,2,3]
if list:
  print("There is counting", list[0])
else:
    print("there is no element")

//functions

def add(a):
  x=a+3
  return x

i=4
i

def add(x,y):
    a=x+y
    return a

print(add (2,3))

// Lambda

square = lambda x: x*x
square(3)

a = lambda x,y : x+y 
r = a(4,7)
print(r)

// list compression

attendance=[23,6,78,30,32]

new_attendance=[]
for i in attendance:
    new_attendance.append(i + 3)

new_attendance

new_attendance=[i+8 for i in attendance]

new_attendance

attendance=[21,56,42,30,34,59]

abv_avg_list=[i for i in attendance if i>=35]

abv_avg_list

// file handling

f = open("myfile.txt", "x")

f = open("myfile.txt", "r")
print(f.read())

f = open("myfile.txt", "a")
f.write("Now the file has more content!")
f.close()

#open and read the file after the appending:
f = open("myfile.txt", "r")
print(f.read())

f = open("myfile.txt", "w")
f.write("Woops! I have deleted the content!")
f.close()

#open and read the file after the appending:
f = open("myfile.txt", "r")
print(f.read())

import os
os.remove("myfile.txt")

import os
if os.path.exists("myfile.txt"):
  os.remove("myfile.txt")
else:
  print("The file does not exist")