# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pDdg1d1Icv0fEkZTK9fCvknKrD7fWZS1
"""

s='hello'
s[0]

'h'

'hello'

s[0:3]

p="hello UMT"
p

p.isdecimal()

p.split()

p.lower()

//listing

my_list=['h','a','s','s','a','n',]
my_list

list = ['Hassan','Siddhu']
print (list)

list*2

list[1]

len(list)

type(list)

del list[0]
list

dir(list)

// Dictionary

a={'1':'val','2':999}
a

a['2']

a={'k1':[1,2,3]}
a

a['k1']

a['k1'][1]

d={'k1':{'inerkey':[7,8,9]}}
d['k1']

city={'LHR':1,'KRCHI':2}
city

len(city)

city['LHR']+=2
city

city.keys()

city.values()

student = {}
student['1']='Ahmad'
student['2']='Ali'
student

// SET

h={1,'a',3,4,6}
h

{2,2,2,2,3,3,3,3,5,5,5,5,5}

h.add(9)
h